name: neurofit_frontend
description: Frontend Web de NeuroFit - Diagnóstico motor y reflejos

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.3.0
  web_socket_channel: ^2.4.0
  provider: ^6.0.5
  fl_chart: ^0.63.0
  pdf: ^3.10.4
  url_launcher: ^6.1.11
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  camera_web: ^0.3.2+1   # Para acceder a la cámara en navegador
  permission_handler: 12.0.1  # Para solicitar permisos de cámara en Android/iOS
  web: ^0.5.1
  intl: ^0.19.0
  path_provider: ^2.1.0
  camera: ^0.10.5+9
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true