# Generated by Django 5.2.13 on 2026-05-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('configuration', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ReactionTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_number', models.IntegerField()),
                ('stimulus_color', models.CharField(max_length=20)),
                ('expected_finger', models.CharField(max_length=20)),
                ('response_finger', models.CharField(blank=True, max_length=20, null=True)),
                ('reaction_time_ms', models.FloatField()),
                ('is_correct', models.BooleanField(default=False)),
                ('ball_trajectory_data', models.JSONField(default=dict)),
                ('hand_landmarks_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
