# Generated by Django 5.2.13 on 2026-05-20 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_diagnosticresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticsession',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='diagnosticsession',
            name='specialist',
        ),
        migrations.RemoveField(
            model_name='reactiontrial',
            name='session',
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('tipo_prueba', models.CharField(max_length=100)),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, max_length=5)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoReflejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_reaccion_ms', models.IntegerField()),
                ('tipo_movimiento', models.CharField(max_length=100)),
                ('precision_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('latencia_registrada_ms', models.IntegerField()),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_reflejo', to='diagnostics.sesion')),
            ],
        ),
        migrations.DeleteModel(
            name='DiagnosticResult',
        ),
        migrations.DeleteModel(
            name='DiagnosticSession',
        ),
        migrations.DeleteModel(
            name='ReactionTrial',
        ),
    ]
